name: CI Pipeline

on:
  push:
    branches:
      - main # Ou a branch que você usa para deploy
  pull_request:
    branches:
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout o código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.10.2" # Versão do Node.js que seu projeto usa

      # Instalar dependências
      - name: Install dependencies
        run: |
          npm install

      # Rodar o Lint
      - name: Run ESLint
        run: npm run lint
